server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: asdqwe123
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#??????
mybatis:
  type-aliases-package: com.duan.entity

  configuration:
    map-underscore-to-camel-case: true

user:
  address:
    max-count: 5